### ISSUE TITLE
Error Using AWQ with 7B Model

### ISSUE THREAD

**Issue by ddemillard** [QwenLM/Qwen2-VL#235] opened 2024-09-20 03:49 UTC
I am able to load and process the full precision 7B model just fine (bfloat 16). However, when I try to import the AWQ model, I get the following error:

```
ValueError: Trying to set a tensor of shape torch.Size([3584]) in "bias" (which has shape torch.Size([8192])), this look incorrect.
```

Here is the code I am running that triggers the error.
```
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info

# default: Load the model on the available device(s)
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-7B-Instruct-AWQ", torch_dtype=torch.float16, device_map="auto"
)
```

I am using an RTX 3090 and I am able to load and use the full precision model `Qwen/Qwen2-VL-7B-Instruct`

**Comment by ahalamora1981** [comment] 2024-09-20 22:35
Same issue with AWQ model.

**Comment by ddemillard** [comment] 2024-09-20 22:48
I can also confirm that the GPTQ-int4 and GPTQ-int8 models works just fine as well per the documentation.

**Comment by kjzju** [comment] 2024-09-24 10:51
Same issue.

**Comment by kq-chen** [comment] 2024-09-24 12:08
Could you please provide more information so that I can reproduce the error? 

Specifically:
1. the full call stack when got error, 
2. The version (commit id) of the transformers installed,
3. maybe env results return by `transformers-cli env` and `python -m torch.utils.collect_env`  can also be helpful.

**Comment by kq-chen** [comment] 2024-09-25 04:27
hi, we have identified the issue. It was caused by an incorrect value for visual.hidden_size in the config in a previous update. 
The [fix](https://huggingface.co/Qwen/Qwen2-VL-7B-Instruct-AWQ/commit/ff3b92ea37451f79ba7d68c0ba42f4171fbd326e) has now been merged. It should now work properly and you can run it directly.

**Closed by kq-chen** 2024-09-25 04:27 UTC
